version: '3.8'
services:

  db:
    ports:
      - "6668:5432"

  loyalty_api:
    environment:
      - DATABASE_URL=postgresql://app:123qwe@db:5432/loyalty
    ports:
      - "8006:8006"

  consumers:
    environment:
      - CALCULATION_OF_POINTS_AMQP_URL=amqp://user:pass@rabbitmq:5672/test
      - CALCULATION_OF_POINTS_CONSUMER_AMQP_URL=amqp://user:pass@rabbitmq:5672/test

  redis:
    ports:
      - "8040:6379"

  rabbitmq:
    ports:
      - "8020:15672"
      - "8030:5672"
